path: "tensorflow.errors.InternalError"
tf_class {
  name: "InternalError"
  is_instance: "<class \'tensorflow.python.framework.errors_impl.InternalError\'>"
  is_instance: "<class \'tensorflow.python.framework.errors_impl.OpError\'>"
  is_instance: "<type \'exceptions.Exception\'>"
  is_instance: "<type \'exceptions.BaseException\'>"
  is_instance: "<type \'object\'>"
  members {
    name: "args"
    mtype: "<type \'getset_descriptor\'>"
  }
  members {
    name: "error_code"
    mtype: "<type \'property\'>"
  }
  members {
    name: "message"
    mtype: "<type \'property\'>"
  }
  members {
    name: "node_def"
    mtype: "<type \'property\'>"
  }
  members {
    name: "op"
    mtype: "<type \'property\'>"
  }
}
